title: masons.codes
description: > # this means to ignore newlines until "baseurl:"
  a website of what i do
baseurl: "/Path-Finding-Algorithm-Visualizer" # the subpath of your site, e.g. /blog
url: "masonhorne.github.io" # the base hostname & protocol for your site
permalink: "/:title/"

author: Mason Horne

include:
  - src

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
