title: Path-Visualizer
description: >
  An interactive path algorithm visualizer.
baseurl: "/Path-Finding-Algorithm-Visualizer"
url: "masonhorne.github.io"
permalink: "/:title/"

author: Mason Horne

include:
  - src

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
